### ISSUE TITLE
two issues with making Freq of my allele plot

### ISSUE THREAD

**Issue by dflackner** [slowkow/allelefrequencies#3]
Error in geom_colh() : could not find function "geom_colh"

I assume that you meant geom_col()

Just curious.  Thanks for this effort.

**Comment by slowkow** [comment]
Hi @dflackner and thanks for opening an issue.

Please see README.Rmd for the full source code: https://github.com/slowkow/allelefrequencies/blob/main/README.Rmd

I'm using `ggstance::geom_colh()`
